<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $inventoryItems = [
            // Paper Products
            [
                'name' => 'A4 Bond Paper (Short)',
                'sku' => 'PAP-A4-SHORT',
                'description' => 'Standard A4 bond paper, 8.5" x 11", 80gsm',
                'quantity' => 5000,
                'min_stock_level' => 500,
                'unit_price' => 0.50,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'A4 Bond Paper (Long)',
                'sku' => 'PAP-A4-LONG',
                'description' => 'A4 long bond paper, 8.5" x 14", 80gsm',
                'quantity' => 3000,
                'min_stock_level' => 300,
                'unit_price' => 0.55,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'A3 Bond Paper',
                'sku' => 'PAP-A3',
                'description' => 'A3 bond paper, 11" x 17", 80gsm',
                'quantity' => 2000,
                'min_stock_level' => 200,
                'unit_price' => 0.75,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Legal Size Paper',
                'sku' => 'PAP-LEGAL',
                'description' => 'Legal size paper, 8.5" x 14", 80gsm',
                'quantity' => 1500,
                'min_stock_level' => 150,
                'unit_price' => 0.60,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Colored Paper (Red)',
                'sku' => 'PAP-COL-RED',
                'description' => 'Red colored paper, A4 size, 80gsm',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.80,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf B1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Colored Paper (Blue)',
                'sku' => 'PAP-COL-BLU',
                'description' => 'Blue colored paper, A4 size, 80gsm',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.80,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf B1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Colored Paper (Yellow)',
                'sku' => 'PAP-COL-YEL',
                'description' => 'Yellow colored paper, A4 size, 80gsm',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.80,
                'unit' => 'reams',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf B1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Glossy Photo Paper (A4)',
                'sku' => 'PAP-GLOSS-A4',
                'description' => 'Glossy photo paper, A4 size, 200gsm',
                'quantity' => 200,
                'min_stock_level' => 50,
                'unit_price' => 2.50,
                'unit' => 'sheets',
                'supplier' => 'Photo Paper Inc.',
                'location' => 'Shelf C1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Matte Photo Paper (A4)',
                'sku' => 'PAP-MATTE-A4',
                'description' => 'Matte photo paper, A4 size, 200gsm',
                'quantity' => 200,
                'min_stock_level' => 50,
                'unit_price' => 2.25,
                'unit' => 'sheets',
                'supplier' => 'Photo Paper Inc.',
                'location' => 'Shelf C1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Cardstock (White)',
                'sku' => 'PAP-CARD-WHT',
                'description' => 'White cardstock, 8.5" x 11", 300gsm',
                'quantity' => 1000,
                'min_stock_level' => 200,
                'unit_price' => 0.15,
                'unit' => 'sheets',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Cardstock (Colored Assorted)',
                'sku' => 'PAP-CARD-COL',
                'description' => 'Assorted colored cardstock, 8.5" x 11", 300gsm',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.20,
                'unit' => 'sheets',
                'supplier' => 'Paper Supplies Co.',
                'location' => 'Shelf A3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Transparency Film',
                'sku' => 'PAP-TRANS',
                'description' => 'Clear transparency film for overhead projectors, A4 size',
                'quantity' => 100,
                'min_stock_level' => 25,
                'unit_price' => 1.50,
                'unit' => 'sheets',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Shelf C2',
                'status' => 'in_stock',
            ],

            // Ink and Toner
            [
                'name' => 'Black Toner Cartridge (Canon)',
                'sku' => 'INK-TON-BLK-CAN',
                'description' => 'Black toner cartridge for Canon printers',
                'quantity' => 15,
                'min_stock_level' => 5,
                'unit_price' => 85.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet D1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Cyan Toner Cartridge (Canon)',
                'sku' => 'INK-TON-CYN-CAN',
                'description' => 'Cyan toner cartridge for Canon printers',
                'quantity' => 10,
                'min_stock_level' => 3,
                'unit_price' => 95.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet D1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Magenta Toner Cartridge (Canon)',
                'sku' => 'INK-TON-MAG-CAN',
                'description' => 'Magenta toner cartridge for Canon printers',
                'quantity' => 10,
                'min_stock_level' => 3,
                'unit_price' => 95.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet D1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Yellow Toner Cartridge (Canon)',
                'sku' => 'INK-TON-YEL-CAN',
                'description' => 'Yellow toner cartridge for Canon printers',
                'quantity' => 10,
                'min_stock_level' => 3,
                'unit_price' => 95.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet D1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Black Ink Cartridge (Epson)',
                'sku' => 'INK-INK-BLK-EP',
                'description' => 'Black ink cartridge for Epson printers',
                'quantity' => 20,
                'min_stock_level' => 8,
                'unit_price' => 45.00,
                'unit' => 'pcs',
                'supplier' => 'Epson Philippines',
                'location' => 'Cabinet D2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'CMYK Ink Set (Epson)',
                'sku' => 'INK-INK-CMYK-EP',
                'description' => 'CMYK ink cartridge set for Epson printers',
                'quantity' => 15,
                'min_stock_level' => 5,
                'unit_price' => 180.00,
                'unit' => 'sets',
                'supplier' => 'Epson Philippines',
                'location' => 'Cabinet D2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Ink Refill Kit (Black)',
                'sku' => 'INK-REF-BLK',
                'description' => 'Black ink refill kit with syringe and bottle',
                'quantity' => 25,
                'min_stock_level' => 10,
                'unit_price' => 150.00,
                'unit' => 'kits',
                'supplier' => 'Ink Refill Solutions',
                'location' => 'Cabinet D3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Ink Refill Kit (Color)',
                'sku' => 'INK-REF-COL',
                'description' => 'Color ink refill kit (CMYK) with syringes and bottles',
                'quantity' => 20,
                'min_stock_level' => 8,
                'unit_price' => 350.00,
                'unit' => 'kits',
                'supplier' => 'Ink Refill Solutions',
                'location' => 'Cabinet D3',
                'status' => 'in_stock',
            ],

            // Binding and Finishing
            [
                'name' => 'Plastic Comb Binding (1/4")',
                'sku' => 'BIND-COMB-14',
                'description' => 'Plastic comb binding spines, 1/4" diameter, holds up to 45 sheets',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.25,
                'unit' => 'pcs',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Plastic Comb Binding (1/2")',
                'sku' => 'BIND-COMB-12',
                'description' => 'Plastic comb binding spines, 1/2" diameter, holds up to 85 sheets',
                'quantity' => 400,
                'min_stock_level' => 80,
                'unit_price' => 0.35,
                'unit' => 'pcs',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Plastic Comb Binding (3/4")',
                'sku' => 'BIND-COMB-34',
                'description' => 'Plastic comb binding spines, 3/4" diameter, holds up to 150 sheets',
                'quantity' => 300,
                'min_stock_level' => 60,
                'unit_price' => 0.45,
                'unit' => 'pcs',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Wire Binding (Double Loop)',
                'sku' => 'BIND-WIRE-DL',
                'description' => 'Double loop wire binding spines, 1/2" diameter',
                'quantity' => 200,
                'min_stock_level' => 50,
                'unit_price' => 0.75,
                'unit' => 'pcs',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Clear Cover Sheets',
                'sku' => 'BIND-COV-CLR',
                'description' => 'Clear plastic cover sheets for binding, A4 size',
                'quantity' => 1000,
                'min_stock_level' => 200,
                'unit_price' => 0.15,
                'unit' => 'sheets',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Black Back Cover Sheets',
                'sku' => 'BIND-COV-BLK',
                'description' => 'Black back cover sheets for binding, A4 size, 300gsm',
                'quantity' => 800,
                'min_stock_level' => 150,
                'unit_price' => 0.20,
                'unit' => 'sheets',
                'supplier' => 'Binding Supplies Co.',
                'location' => 'Shelf E3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Laminating Pouches (A4)',
                'sku' => 'LAM-A4',
                'description' => 'Laminating pouches, A4 size, 80 micron',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.50,
                'unit' => 'pcs',
                'supplier' => 'Laminating Solutions',
                'location' => 'Shelf F1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Laminating Pouches (Letter)',
                'sku' => 'LAM-LTR',
                'description' => 'Laminating pouches, Letter size, 80 micron',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 0.50,
                'unit' => 'pcs',
                'supplier' => 'Laminating Solutions',
                'location' => 'Shelf F1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Laminating Pouches (A3)',
                'sku' => 'LAM-A3',
                'description' => 'Laminating pouches, A3 size, 80 micron',
                'quantity' => 200,
                'min_stock_level' => 50,
                'unit_price' => 0.75,
                'unit' => 'pcs',
                'supplier' => 'Laminating Solutions',
                'location' => 'Shelf F1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Laminating Roll (Cold)',
                'sku' => 'LAM-ROLL-COLD',
                'description' => 'Cold laminating roll, 24" x 100ft',
                'quantity' => 5,
                'min_stock_level' => 2,
                'unit_price' => 450.00,
                'unit' => 'rolls',
                'supplier' => 'Laminating Solutions',
                'location' => 'Shelf F2',
                'status' => 'in_stock',
            ],

            // Office Supplies
            [
                'name' => 'Staples (Standard)',
                'sku' => 'OFF-STAP-STD',
                'description' => 'Standard staples, 26/6 size',
                'quantity' => 50,
                'min_stock_level' => 10,
                'unit_price' => 25.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Staples (Heavy Duty)',
                'sku' => 'OFF-STAP-HVY',
                'description' => 'Heavy duty staples, 24/6 size',
                'quantity' => 30,
                'min_stock_level' => 8,
                'unit_price' => 35.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Paper Clips (Small)',
                'sku' => 'OFF-CLIP-SML',
                'description' => 'Small paper clips, #1 size',
                'quantity' => 100,
                'min_stock_level' => 20,
                'unit_price' => 15.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Paper Clips (Large)',
                'sku' => 'OFF-CLIP-LRG',
                'description' => 'Large paper clips, #2 size',
                'quantity' => 80,
                'min_stock_level' => 15,
                'unit_price' => 18.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Binder Clips (Small)',
                'sku' => 'OFF-BIND-SML',
                'description' => 'Small binder clips, 19mm',
                'quantity' => 50,
                'min_stock_level' => 10,
                'unit_price' => 45.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Binder Clips (Medium)',
                'sku' => 'OFF-BIND-MED',
                'description' => 'Medium binder clips, 32mm',
                'quantity' => 40,
                'min_stock_level' => 8,
                'unit_price' => 55.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Binder Clips (Large)',
                'sku' => 'OFF-BIND-LRG',
                'description' => 'Large binder clips, 51mm',
                'quantity' => 30,
                'min_stock_level' => 6,
                'unit_price' => 65.00,
                'unit' => 'boxes',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Folders (Clear)',
                'sku' => 'OFF-FOLD-CLR',
                'description' => 'Clear plastic folders, A4 size',
                'quantity' => 200,
                'min_stock_level' => 50,
                'unit_price' => 8.00,
                'unit' => 'pcs',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Shelf H1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Folders (Colored Assorted)',
                'sku' => 'OFF-FOLD-COL',
                'description' => 'Assorted colored folders, A4 size',
                'quantity' => 300,
                'min_stock_level' => 75,
                'unit_price' => 10.00,
                'unit' => 'pcs',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Shelf H1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Envelope (Short)',
                'sku' => 'OFF-ENV-SRT',
                'description' => 'Short brown envelope, 9" x 4"',
                'quantity' => 500,
                'min_stock_level' => 100,
                'unit_price' => 2.00,
                'unit' => 'pcs',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Shelf H2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Envelope (Long)',
                'sku' => 'OFF-ENV-LNG',
                'description' => 'Long brown envelope, 12" x 4"',
                'quantity' => 400,
                'min_stock_level' => 80,
                'unit_price' => 2.50,
                'unit' => 'pcs',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Shelf H2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Scotch Tape (Clear)',
                'sku' => 'OFF-TAPE-CLR',
                'description' => 'Clear scotch tape, 1" x 20 yards',
                'quantity' => 60,
                'min_stock_level' => 15,
                'unit_price' => 25.00,
                'unit' => 'rolls',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G4',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Masking Tape',
                'sku' => 'OFF-TAPE-MSK',
                'description' => 'Masking tape, 1" x 60 yards',
                'quantity' => 40,
                'min_stock_level' => 10,
                'unit_price' => 30.00,
                'unit' => 'rolls',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G4',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Glue Stick',
                'sku' => 'OFF-GLUE-STK',
                'description' => 'Glue stick, 20g',
                'quantity' => 100,
                'min_stock_level' => 25,
                'unit_price' => 12.00,
                'unit' => 'pcs',
                'supplier' => 'Office Supplies Ltd.',
                'location' => 'Drawer G5',
                'status' => 'in_stock',
            ],

            // Equipment Parts and Maintenance
            [
                'name' => 'Printer Cleaning Kit',
                'sku' => 'EQP-CLN-KIT',
                'description' => 'Printer head cleaning kit with solution and swabs',
                'quantity' => 10,
                'min_stock_level' => 3,
                'unit_price' => 350.00,
                'unit' => 'kits',
                'supplier' => 'Printer Maintenance Co.',
                'location' => 'Cabinet I1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Fuser Unit (Canon)',
                'sku' => 'EQP-FUS-CAN',
                'description' => 'Replacement fuser unit for Canon printers',
                'quantity' => 2,
                'min_stock_level' => 1,
                'unit_price' => 2500.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet I2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Transfer Belt (Canon)',
                'sku' => 'EQP-TRN-CAN',
                'description' => 'Replacement transfer belt for Canon printers',
                'quantity' => 2,
                'min_stock_level' => 1,
                'unit_price' => 1800.00,
                'unit' => 'pcs',
                'supplier' => 'Canon Philippines',
                'location' => 'Cabinet I2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Maintenance Kit (Epson)',
                'sku' => 'EQP-MNT-EP',
                'description' => 'Maintenance kit for Epson printers',
                'quantity' => 3,
                'min_stock_level' => 1,
                'unit_price' => 1200.00,
                'unit' => 'kits',
                'supplier' => 'Epson Philippines',
                'location' => 'Cabinet I3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Cutting Blade (Guillotine)',
                'sku' => 'EQP-BLD-GUI',
                'description' => 'Replacement cutting blade for guillotine cutter',
                'quantity' => 3,
                'min_stock_level' => 1,
                'unit_price' => 850.00,
                'unit' => 'pcs',
                'supplier' => 'Cutting Equipment Co.',
                'location' => 'Cabinet I4',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Laminating Film Roll (Hot)',
                'sku' => 'EQP-LAM-HOT',
                'description' => 'Hot laminating film roll, 27" x 300ft',
                'quantity' => 4,
                'min_stock_level' => 2,
                'unit_price' => 1200.00,
                'unit' => 'rolls',
                'supplier' => 'Laminating Solutions',
                'location' => 'Shelf F3',
                'status' => 'in_stock',
            ],

            // Specialty Items
            [
                'name' => 'Sticker Paper (Glossy)',
                'sku' => 'SPC-STK-GLS',
                'description' => 'Glossy sticker paper, A4 size, waterproof',
                'quantity' => 150,
                'min_stock_level' => 30,
                'unit_price' => 3.50,
                'unit' => 'sheets',
                'supplier' => 'Specialty Paper Co.',
                'location' => 'Shelf J1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Sticker Paper (Matte)',
                'sku' => 'SPC-STK-MAT',
                'description' => 'Matte sticker paper, A4 size, waterproof',
                'quantity' => 150,
                'min_stock_level' => 30,
                'unit_price' => 3.25,
                'unit' => 'sheets',
                'supplier' => 'Specialty Paper Co.',
                'location' => 'Shelf J1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Magnetic Paper',
                'sku' => 'SPC-MAG',
                'description' => 'Magnetic paper for printing magnets, A4 size',
                'quantity' => 100,
                'min_stock_level' => 25,
                'unit_price' => 5.00,
                'unit' => 'sheets',
                'supplier' => 'Specialty Paper Co.',
                'location' => 'Shelf J2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Canvas Paper',
                'sku' => 'SPC-CNV',
                'description' => 'Canvas paper for art prints, A4 size',
                'quantity' => 80,
                'min_stock_level' => 20,
                'unit_price' => 4.50,
                'unit' => 'sheets',
                'supplier' => 'Specialty Paper Co.',
                'location' => 'Shelf J2',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Iron-on Transfer Paper',
                'sku' => 'SPC-IRON',
                'description' => 'Iron-on transfer paper for t-shirts, A4 size',
                'quantity' => 100,
                'min_stock_level' => 25,
                'unit_price' => 4.00,
                'unit' => 'sheets',
                'supplier' => 'Specialty Paper Co.',
                'location' => 'Shelf J3',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Vinyl Roll (White)',
                'sku' => 'SPC-VIN-WHT',
                'description' => 'White vinyl roll for stickers and decals, 24" x 50ft',
                'quantity' => 5,
                'min_stock_level' => 2,
                'unit_price' => 1800.00,
                'unit' => 'rolls',
                'supplier' => 'Signage Supplies Co.',
                'location' => 'Shelf K1',
                'status' => 'in_stock',
            ],
            [
                'name' => 'Vinyl Roll (Black)',
                'sku' => 'SPC-VIN-BLK',
                'description' => 'Black vinyl roll for stickers and decals, 24" x 50ft',
                'quantity' => 5,
                'min_stock_level' => 2,
                'unit_price' => 1800.00,
                'unit' => 'rolls',
                'supplier' => 'Signage Supplies Co.',
                'location' => 'Shelf K1',
                'status' => 'in_stock',
            ],
        ];

        foreach ($inventoryItems as $item) {
            Inventory::create($item);
        }
    }
}
